@startuml

title Détails des composants interne/externe

/' = = = = = = = COMPONENT = = = = = = = '/

actor client
actor employee
actor bank

cloud internet

node frontoffice
node backoffice

database database

/' = = = = = = = RELATION = = = = = = = '/

client -down- internet
bank -up- internet
internet -left- frontoffice
employee -down- frontoffice
employee - backoffice

frontoffice -down- database
database -up- backoffice

@enduml
