/' = = = = = = = ATTRIBUTE = = = = = = = '/
class address {
    att(Label,String,VARCHAR(30))
    att(name,String,VARCHAR(30))
    att(line1,String,VARCHAR(20))
    att(line2,String,VARCHAR(20))
    att(zip,String,VARCHAR(5))
    att(city,String,VARCHAR(20))
}
class client {
    att(1st_name,String,VARCHAR(30))
    att(name,String,VARCHAR(30))
    att(mail,String,VARCHAR(30))
    att(login,String,VARCHAR(30))
    att(password,String,VARCHAR(30))
}
class composition {
    att(quantity,Real,DECIMAL(6,2))
}
class employee {
    att(1st_name,String,VARCHAR(30))
    att(name,String,VARCHAR(30))
    att(mail,String,VARCHAR(30))
    att(login,String,VARCHAR(30))
    att(password,String,VARCHAR(30))
}
class ingredient {
    label,String,VARCHAR(30))
    att(unit,String,VARCHAR(30))
}
class line_basket {
    att(quantity,Integer,INTEGER)
    att(tax_rate100,Real,DECIMAL(6,2))
    att(unit_price_ex_tax,Real,DECIMAL(6,2))
}
class basket {
    att(invoice_num,String,VARCHAR(10))
    att(date,Date,DATETIME)
    att(status,String,VARCHAR(10))
}
class payment_history {
    att(amount,Real,DECIMAL(6,2))
    att(date,Date,DATETIME)
}
class payment_solution {
    att(label,String,VARCHAR(30))
}
class pizza {
    att(name,String,VARCHAR(10))
    att(unit_price_ex_tax,Real,DECIMAL(6,2))
    att(tax_rate100,Real,DECIMAL(6,2))
}
class phone {
    att(number,String,VARCHAR(10))
}
class restaurant {
    att(name,String,VARCHAR(10))
}
class stock {
    att(quantity,Real,DECIMAL(6,2))
}
