/' = = = = = = = ATTRIBUTE = = = = = = = '/
class address {
    Label: String
    name: String
    line1: String
    line2: String
    zip: String
    city: String
}
class client {
    1st_name: String
    name: String
    mail: String
    login: String
    password: String
}
class composition {
    quantity: Real
}
class employee {
    1st_name: String
    name: String
    mail: String
    login: String
    password: String
}
class ingredient {
    label: String
    unit: String
}
class line_order {
    quantity: Integer
    tax_rate100: Real
    unit_price_ex_tax: Real
}
class order {
    invoice_num: String
    date: Date
    status: String
}
class payment_history {
    amount: Real
    date: Date
}
class payment_solution {
    label: String
}
class pizza {
    name: String
    unit_price_ex_tax: Real
    tax_rate100: Real
}
class phone {
    number: String
}
class restaurant {
    name: String
}
class stock {
    quantity: Real
}
