/' = = = = = = = CLASSE = = = = = = = '/
class address
class client
class composition
class employee
class ingredient
class line_order
class order
class payment_history
class payment_solution
class phone
class pizza
class restaurant
class stock

/' = = = = = = = RELATION = = = = = = = '/
address "1" -- "1" restaurant
address "1" -- "*" employee
client "1*" - "1..2*" phone
client "1..2*" -- "1..2*" address
employee "1" - "*" order
employee "*" -right- "1" restaurant
ingredient "1..*" -- "1..*" restaurant
(ingredient, restaurant) .. stock
line_order "*" -- "1" order
line_order "1" - "*" pizza
order "*" - "1" client
order "1" - "*" restaurant
order "1" -left- "*" payment_history
payment_solution "1" -up- "*" payment_history
phone "1" -- "1..2" employee
phone "1" -- "1" restaurant
pizza "1..*" - "1..*" ingredient
(pizza, ingredient) .. composition
