/' = = = = = = = CLASSE = = = = = = = '/
class address
class client
class composition <<assoc>>
class employee
class ingredient
class line_order
class order
class payment_history
class payment_solution
class phone
class pizza
class restaurant
class stock <<assoc>>

/' = = = = = = = RELATION = = = = = = = '/
rel(address,1,--,1,restaurant)
rel(address,1,--,*,employee)
rel(client,1,--,1..2,phone)
rel(client,1..2,--,1..2,address)
rel(employee,1,-,*,order)
rel(line_order,*,--,1,order)
rel(line_order,1,-,*,pizza)
rel(order,*,-,1,client)
rel(order,1,-,*,restaurant)
rel(order,1,-left-,*,payment_history)
rel(payment_solution,1,-up-,*,payment_history)
rel(phone,1,--,1..2,employee)
rel(phone,1,--,1,restaurant)
