@startuml
title Diagramme de déploiement «OCPweb»

/' = = = = = = = STYLE = = = = = = = '/
' skinparam monochrome true
' skinparam linetype ortho

cloud "PayPal server" as bank <<system>>
actor "Employee" <<LAN>>
cloud "Clients" <<internet>>

/' = = = = = = = ARTIFACT = = = = = = = '/

Frame  "OCPweb" {

    node "Nginx\n HTTP server" as nginx

    database "PostgreSQL\n server" as psql

    node "File system" as fs {
        node "staticfiles" as stat
    }

    node "supervisor" as supervisor {
        node "Gunicorn WSGI\n HTTP server" as gunicorn
        node "Django" as django
    }

}

/' = = = = = = = RELATION = = = = = = = '/

bank -up- nginx
Clients -up- nginx
Employee -up- nginx

django .. stat
django - gunicorn
gunicorn -- nginx
nginx - stat
django -up- psql

@enduml
