@startuml

title Description du domaine fonctionnel\n

/' = = = = = = = STYLE = = = = = = = '/
skinparam monochrome true
hide empty methods

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a c e
!define rea(a,b,c,d) (a, b) c d

/' = = = = = = = CLASSE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/classes.iuml

/' = = = = = = = ASSOCIATION = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/associations.iuml


@enduml
