@startuml

title Description du domaine fonctionnel\n Diagramme de classe.\n

/' = = = = = = = STYLE = = = = = = = '/
hide empty methods

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a "b" c "d" e
!define rea(a,b,c,d) (a, b) c d

/' = = = = = = = CLASSE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/classes.iuml

/' = = = = = = = ATTRIBUTE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/attributes.iuml

/' = = = = = = = ASSOCIATION = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/associations.iuml

@enduml
