@startuml

title Description du domaine fonctionnel\n Diagramme de classe.\n

/' = = = = = = = STYLE = = = = = = = '/
hide empty methods
hide circle

/' = = = = = = = CLASSE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/classes.iuml

/' = = = = = = = ATTRIBUTE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/attributes.iuml

@enduml
