/' = = = = = = = KEY = = = = = = = '/
class address {
    pyk(id,Integer)
}
class client {
    pyk(id, Integer)
    fnk(delivery_address_id,address.id)
    fnk(billing_address_id,address.id)
}
class composition {
    pfk(pizza_id,pizza.id)
    pfk(ingredient_id,ingredient.id)
}
class employee {
    pyk(id,Integer)
    fnk(address_id,address.id)
    fnk(phone_id,phone.id)
}
class ingredient {
    pyk(id,Integer)
}
class line_basket {
    pyk(id,Integer)
    fnk(basket_id,basket.id)
    fnk(pizza_id,pizza.id)
}
class basket {
    pyk(id,Integer)
    fnk(employee_id,employee.id)
    fnk(client_id,client.id)
    fnk(restaurant_id,restaurant.id)
}
class payment_history {
    pfk(payment_solution_id,payment_solution.id)
    pfk(basket_id,basket.id)
}
class payment_solution {
    pyk(id,Integer)
}
class phone {
    pyk(id,Integer)
}
class pizza {
    pyk(id,Integer)
}
class restaurant {
    pyk(id,Integer)
    fnk(address_id,address.id)
    fnk(phone_id,phone.id)
}
class stock {
    pfk(ingredient_id,ingredient.id)
    pfk(restaurant_id,restaurant.id)
}
