@startuml

title Modèle physique de donnée\n

/' = = = = = = = STYLE = = = = = = = '/
hide empty methods
hide circle
skinparam class {
    BackgroundColor<<assoc>> lightblue
}

/' = = = = = = = MACRO = = = = = = = '/
!define rel(a,b,c,d,e) a c e
!define rea(a,b,c,d) (a, b) c d
!define pyk(n,t="INTEGER") <font color="red">n : t [PK]</font>
!define fnk(n,r,t="INTEGER") <font color="blue">n : t [FK]</font>
!define pfk(n,r,t="INTEGER") <font color="orangered">n : t [PFK]</font>
!define att(n,u,s) n : s

/' = = = = = = = CLASSE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/classes.iuml

/' = = = = = = = KEY = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/keys.iuml

/' = = = = = = = ATTRIBUTE = = = = = = = '/
!includeurl https://raw.githubusercontent.com/freezed/ocp6/master/src-puml/attributes.iuml

/' = = = = = = = ASSOCIATION = = = = = = = '/
rel(pizza,.,-,.,composition)
rel(composition,.,-,.,ingredient)
rel(ingredient,.,--,.,stock)
rel(stock,.,--,.,restaurant)

@enduml
